language: objective-c
osx_image: xcode8.1

script:
- set -o pipefail
- xcodebuild clean build test -workspace ./ChattoApp/ChattoApp.xcworkspace -scheme ChattoApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
- rm -rf ~/Library/Developer/Xcode/DerivedData
- xcodebuild clean build test -workspace ./Chatto.xcworkspace -scheme Chatto -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
- (curl -s https://codecov.io/bash) | bash
- rm -rf ~/Library/Developer/Xcode/DerivedData
- xcodebuild clean build test -workspace ./Chatto.xcworkspace -scheme ChattoAdditions -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
- (curl -s https://codecov.io/bash) | bash
